chore: update validate job

diff --git a/.github/workflows/validate.yml b/.github/workflows/validate.yml
--- a/.github/workflows/validate.yml
+++ b/.github/workflows/validate.yml
@@ -29,6 +29,17 @@ jobs:
         with:
           tflint_version: latest
 
+      - name: Generate documentation
+        run: make generate-docs
+
+      - name: Check for documentation changes
+        run: |
+          if ! git diff --exit-code README.md; then
+            echo "Error: Documentation is out of date. Please run 'make generate-docs' and commit the changes."
+            exit 1
+          fi
+          echo "Documentation is up to date."
+
       - name: Terraform Init
         run: terraform init
 
@@ -54,14 +65,3 @@ jobs:
               cd -
             fi
           done
-
-      - name: Generate documentation
-        run: make generate-docs
-
-      - name: Check for documentation changes
-        run: |
-          if ! git diff --exit-code README.md; then
-            echo "Error: Documentation is out of date. Please run 'make generate-docs' and commit the changes."
-            exit 1
-          fi
-          echo "Documentation is up to date."
